version: "3"
services:
  bot:
    build:
      context: ../../
      dockerfile: script/docker/bot.Dockerfile
    networks:
      - bot-net
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4318:4318"
    networks:
      - bot-net
networks:
  bot-net:
    driver: bridge