log_level: "info"
bot_token: "tg-bot-token"
profanity:
  # dynamic repeated symbol
  dynamic: "*" 
  # static text
  static: "{censored}"
rabbit:
  url: "rabbit_mq_url"
  msg_queue: "msg_processor_queue"
  workers_count: 10

