log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "tg-bot"
bot:
  token: "tg-bot-token"
  update_timeout_seconds: 5
profanity:
  # dynamic repeated symbol
  dynamic: "*" 
  # static text
  static: "{censored}"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
command_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 0
  ttl: 5m
ban_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 1
  ban_ttl: 5m
  violations_per_hour: 3

