log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "tg-bot"
bot:
  token: "tg-bot-token"
  update_timeout_seconds: 5
profanity:
  # dynamic repeated symbol
  dynamic: "*" 
  # static text
  static: "{censored}"

